# backend/pytest.ini
[pytest]
asyncio_mode = strict
filterwarnings =
    ignore:Support for class-based `config` is deprecated:UserWarning
    ignore:Accessing argon2.__version__ is deprecated:DeprecationWarning
    # Ajoute cette ligne pour être plus large sur Pydantic
    ignore::pydantic.PydanticDeprecatedSince20